//! Do NOT edit this code.
//! It was automatically generated by Pavex.
//! All manual edits will be lost next time the code is generated.
extern crate alloc;
struct ServerState {
    router: Router,
    application_state: ApplicationState,
}
#[derive(Debug, Clone, serde::Deserialize)]
pub struct ApplicationConfig {
    pub auth: app::configuration::AuthConfig,
    pub database: app::configuration::DatabaseConfig,
    pub server: app::configuration::ServerConfig,
}
pub struct ApplicationState {
    pub encoding_key: jsonwebtoken::EncodingKey,
    pub pool: sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
}
impl ApplicationState {
    pub async fn new(
        app_config: crate::ApplicationConfig,
    ) -> Result<crate::ApplicationState, crate::ApplicationStateError> {
        Self::_new(&app_config.auth, &app_config.database).await
    }
    async fn _new(
        v0: &app::configuration::AuthConfig,
        v1: &app::configuration::DatabaseConfig,
    ) -> Result<crate::ApplicationState, crate::ApplicationStateError> {
        let v2 = app::configuration::AuthConfig::encoding_key(v0);
        let v3 = match v2 {
            Ok(ok) => ok,
            Err(v3) => {
                return {
                    let v4 = crate::ApplicationStateError::AuthConfigEncodingKey(v3);
                    core::result::Result::Err(v4)
                };
            }
        };
        let v4 = app::configuration::DatabaseConfig::get_pool(v1).await;
        let v5 = match v4 {
            Ok(ok) => ok,
            Err(v5) => {
                return {
                    let v6 = crate::ApplicationStateError::DatabaseConfigGetPool(v5);
                    core::result::Result::Err(v6)
                };
            }
        };
        let v6 = crate::ApplicationState {
            encoding_key: v3,
            pool: v5,
        };
        core::result::Result::Ok(v6)
    }
}
#[derive(Debug, thiserror::Error)]
pub enum ApplicationStateError {
    #[error(transparent)]
    AuthConfigEncodingKey(jsonwebtoken::errors::Error),
    #[error(transparent)]
    DatabaseConfigGetPool(sqlx_core::Error),
}
pub fn run(
    server_builder: pavex::server::Server,
    application_state: ApplicationState,
) -> pavex::server::ServerHandle {
    async fn handler(
        request: http::Request<hyper::body::Incoming>,
        connection_info: Option<pavex::connection::ConnectionInfo>,
        server_state: std::sync::Arc<ServerState>,
    ) -> pavex::Response {
        let (router, state) = (&server_state.router, &server_state.application_state);
        router.route(request, connection_info, state).await
    }
    let router = Router::new();
    let server_state = std::sync::Arc::new(ServerState {
        router,
        application_state,
    });
    server_builder.serve(handler, server_state)
}
struct Router {
    router: matchit::Router<u32>,
}
impl Router {
    /// Create a new router instance.
    ///
    /// This method is invoked once, when the server starts.
    pub fn new() -> Self {
        Self { router: Self::router() }
    }
    fn router() -> matchit::Router<u32> {
        let mut router = matchit::Router::new();
        router.insert("/api/users", 0u32).unwrap();
        router.insert("/api/users/login", 1u32).unwrap();
        router.insert("/users", 2u32).unwrap();
        router.insert("/users/login", 3u32).unwrap();
        router
    }
    pub async fn route(
        &self,
        request: http::Request<hyper::body::Incoming>,
        _connection_info: Option<pavex::connection::ConnectionInfo>,
        #[allow(unused)]
        state: &ApplicationState,
    ) -> pavex::Response {
        let (request_head, request_body) = request.into_parts();
        let request_head: pavex::request::RequestHead = request_head.into();
        let request_body = pavex::request::body::RawIncomingBody::from(request_body);
        let Ok(matched_route) = self.router.at(&request_head.target.path()) else {
            let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter(
                    vec![],
                )
                .into();
            let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                "*",
            );
            return route_0::entrypoint(
                    matched_route_template,
                    &allowed_methods,
                    &request_head,
                )
                .await;
        };
        match matched_route.value {
            0u32 => {
                match &request_head.method {
                    &pavex::http::Method::POST => {
                        let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                            "/api/users",
                        );
                        route_4::entrypoint(
                                matched_route_template,
                                request_body,
                                &request_head,
                                &state.pool,
                                &state.encoding_key,
                            )
                            .await
                    }
                    _ => {
                        let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                                pavex::http::Method::POST,
                            ])
                            .into();
                        let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                            "/api/users",
                        );
                        route_0::entrypoint(
                                matched_route_template,
                                &allowed_methods,
                                &request_head,
                            )
                            .await
                    }
                }
            }
            1u32 => {
                match &request_head.method {
                    &pavex::http::Method::POST => {
                        let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                            "/api/users/login",
                        );
                        route_3::entrypoint(
                                matched_route_template,
                                request_body,
                                &request_head,
                                &state.pool,
                                &state.encoding_key,
                            )
                            .await
                    }
                    _ => {
                        let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                                pavex::http::Method::POST,
                            ])
                            .into();
                        let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                            "/api/users/login",
                        );
                        route_0::entrypoint(
                                matched_route_template,
                                &allowed_methods,
                                &request_head,
                            )
                            .await
                    }
                }
            }
            2u32 => {
                match &request_head.method {
                    &pavex::http::Method::POST => {
                        let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                            "/users",
                        );
                        route_2::entrypoint(
                                matched_route_template,
                                request_body,
                                &request_head,
                                &state.pool,
                                &state.encoding_key,
                            )
                            .await
                    }
                    _ => {
                        let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                                pavex::http::Method::POST,
                            ])
                            .into();
                        let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                            "/users",
                        );
                        route_0::entrypoint(
                                matched_route_template,
                                &allowed_methods,
                                &request_head,
                            )
                            .await
                    }
                }
            }
            3u32 => {
                match &request_head.method {
                    &pavex::http::Method::POST => {
                        let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                            "/users/login",
                        );
                        route_1::entrypoint(
                                matched_route_template,
                                request_body,
                                &request_head,
                                &state.pool,
                                &state.encoding_key,
                            )
                            .await
                    }
                    _ => {
                        let allowed_methods: pavex::router::AllowedMethods = pavex::router::MethodAllowList::from_iter([
                                pavex::http::Method::POST,
                            ])
                            .into();
                        let matched_route_template = pavex::request::path::MatchedPathPattern::new(
                            "/users/login",
                        );
                        route_0::entrypoint(
                                matched_route_template,
                                &allowed_methods,
                                &request_head,
                            )
                            .await
                    }
                }
            }
            i => unreachable!("Unknown route id: {}", i),
        }
    }
}
pub mod route_0 {
    pub async fn entrypoint<'a, 'b>(
        s_0: pavex::request::path::MatchedPathPattern,
        s_1: &'a pavex::router::AllowedMethods,
        s_2: &'b pavex::request::RequestHead,
    ) -> pavex::Response {
        let response = wrapping_0(s_0, s_1, s_2).await;
        response
    }
    async fn stage_1<'a, 'b>(
        s_0: &'a pavex::router::AllowedMethods,
        s_1: pavex::request::path::MatchedPathPattern,
        s_2: &'b pavex::request::RequestHead,
    ) -> pavex::Response {
        let response = wrapping_1(s_1, s_2, s_0).await;
        response
    }
    async fn stage_2<'a, 'b>(
        s_0: &'a pavex_tracing::RootSpan,
        s_1: &'b pavex::router::AllowedMethods,
    ) -> pavex::Response {
        let response = handler(s_1).await;
        let response = post_processing_0(response, s_0).await;
        response
    }
    async fn wrapping_0(
        v0: pavex::request::path::MatchedPathPattern,
        v1: &pavex::router::AllowedMethods,
        v2: &pavex::request::RequestHead,
    ) -> pavex::Response {
        let v3 = crate::route_0::Next0 {
            s_0: v1,
            s_1: v0,
            s_2: v2,
            next: stage_1,
        };
        let v4 = pavex::middleware::Next::new(v3);
        let v5 = pavex::middleware::wrap_noop(v4).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v5)
    }
    async fn wrapping_1(
        v0: pavex::request::path::MatchedPathPattern,
        v1: &pavex::request::RequestHead,
        v2: &pavex::router::AllowedMethods,
    ) -> pavex::Response {
        let v3 = pavex::telemetry::ServerRequestId::generate();
        let v4 = app::telemetry::root_span(v1, v0, v3);
        let v5 = crate::route_0::Next1 {
            s_0: &v4,
            s_1: v2,
            next: stage_2,
        };
        let v6 = pavex::middleware::Next::new(v5);
        let v7 = <pavex_tracing::RootSpan as core::clone::Clone>::clone(&v4);
        let v8 = pavex_tracing::logger(v7, v6).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v8)
    }
    async fn handler(v0: &pavex::router::AllowedMethods) -> pavex::Response {
        let v1 = pavex::router::default_fallback(v0).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v1)
    }
    async fn post_processing_0(
        v0: pavex::Response,
        v1: &pavex_tracing::RootSpan,
    ) -> pavex::Response {
        let v2 = app::telemetry::response_logger(v0, v1).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v2)
    }
    struct Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        s_0: &'a pavex::router::AllowedMethods,
        s_1: pavex::request::path::MatchedPathPattern,
        s_2: &'b pavex::request::RequestHead,
        next: fn(
            &'a pavex::router::AllowedMethods,
            pavex::request::path::MatchedPathPattern,
            &'b pavex::request::RequestHead,
        ) -> T,
    }
    impl<'a, 'b, T> std::future::IntoFuture for Next0<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        type Output = pavex::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2)
        }
    }
    struct Next1<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        s_0: &'a pavex_tracing::RootSpan,
        s_1: &'b pavex::router::AllowedMethods,
        next: fn(&'a pavex_tracing::RootSpan, &'b pavex::router::AllowedMethods) -> T,
    }
    impl<'a, 'b, T> std::future::IntoFuture for Next1<'a, 'b, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        type Output = pavex::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1)
        }
    }
}
pub mod route_1 {
    pub async fn entrypoint<'a, 'b, 'c>(
        s_0: pavex::request::path::MatchedPathPattern,
        s_1: pavex::request::body::RawIncomingBody,
        s_2: &'a pavex::request::RequestHead,
        s_3: &'b sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_4: &'c jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let response = wrapping_0(s_0, s_1, s_2, s_3, s_4).await;
        response
    }
    async fn stage_1<'a, 'b, 'c>(
        s_0: pavex::request::body::RawIncomingBody,
        s_1: &'a pavex::request::RequestHead,
        s_2: &'b sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_3: &'c jsonwebtoken::EncodingKey,
        s_4: pavex::request::path::MatchedPathPattern,
    ) -> pavex::Response {
        let response = wrapping_1(s_0, s_4, s_1, s_2, s_3).await;
        response
    }
    async fn stage_2<'a, 'b, 'c, 'd>(
        s_0: &'a pavex_tracing::RootSpan,
        s_1: pavex::request::body::RawIncomingBody,
        s_2: &'b pavex::request::RequestHead,
        s_3: &'c sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_4: &'d jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let response = handler(s_1, s_2, s_0, s_3, s_4).await;
        let response = post_processing_0(response, s_0).await;
        response
    }
    async fn wrapping_0(
        v0: pavex::request::path::MatchedPathPattern,
        v1: pavex::request::body::RawIncomingBody,
        v2: &pavex::request::RequestHead,
        v3: &sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        v4: &jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let v5 = crate::route_1::Next0 {
            s_0: v1,
            s_1: v2,
            s_2: v3,
            s_3: v4,
            s_4: v0,
            next: stage_1,
        };
        let v6 = pavex::middleware::Next::new(v5);
        let v7 = pavex::middleware::wrap_noop(v6).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v7)
    }
    async fn wrapping_1(
        v0: pavex::request::body::RawIncomingBody,
        v1: pavex::request::path::MatchedPathPattern,
        v2: &pavex::request::RequestHead,
        v3: &sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        v4: &jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let v5 = pavex::telemetry::ServerRequestId::generate();
        let v6 = app::telemetry::root_span(v2, v1, v5);
        let v7 = crate::route_1::Next1 {
            s_0: &v6,
            s_1: v0,
            s_2: v2,
            s_3: v3,
            s_4: v4,
            next: stage_2,
        };
        let v8 = pavex::middleware::Next::new(v7);
        let v9 = <pavex_tracing::RootSpan as core::clone::Clone>::clone(&v6);
        let v10 = pavex_tracing::logger(v9, v8).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v10)
    }
    async fn handler(
        v0: pavex::request::body::RawIncomingBody,
        v1: &pavex::request::RequestHead,
        v2: &pavex_tracing::RootSpan,
        v3: &sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        v4: &jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let v5 = pavex::request::body::BodySizeLimit::new();
        let v6 = pavex::request::body::BufferedBody::extract(v1, v0, v5).await;
        let v7 = match v6 {
            Ok(ok) => ok,
            Err(v7) => {
                return {
                    let v8 = pavex::request::body::errors::ExtractBufferedBodyError::into_response(
                        &v7,
                    );
                    let v9 = pavex::Error::new(v7);
                    app::telemetry::error_logger(&v9, v2).await;
                    <pavex::Response as pavex::IntoResponse>::into_response(v8)
                };
            }
        };
        let v8 = pavex::request::body::JsonBody::extract(v1, &v7);
        let v9 = match v8 {
            Ok(ok) => ok,
            Err(v9) => {
                return {
                    let v10 = pavex::request::body::errors::ExtractJsonBodyError::into_response(
                        &v9,
                    );
                    let v11 = pavex::Error::new(v9);
                    app::telemetry::error_logger(&v11, v2).await;
                    <pavex::Response as pavex::IntoResponse>::into_response(v10)
                };
            }
        };
        let v10 = app::routes::users::login(v9, v3, v4).await;
        let v11 = match v10 {
            Ok(ok) => ok,
            Err(v11) => {
                return {
                    let v12 = app::routes::users::LoginError::into_response(&v11);
                    let v13 = pavex::Error::new(v11);
                    app::telemetry::error_logger(&v13, v2).await;
                    <pavex::Response as pavex::IntoResponse>::into_response(v12)
                };
            }
        };
        <pavex::Response as pavex::IntoResponse>::into_response(v11)
    }
    async fn post_processing_0(
        v0: pavex::Response,
        v1: &pavex_tracing::RootSpan,
    ) -> pavex::Response {
        let v2 = app::telemetry::response_logger(v0, v1).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v2)
    }
    struct Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        s_0: pavex::request::body::RawIncomingBody,
        s_1: &'a pavex::request::RequestHead,
        s_2: &'b sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_3: &'c jsonwebtoken::EncodingKey,
        s_4: pavex::request::path::MatchedPathPattern,
        next: fn(
            pavex::request::body::RawIncomingBody,
            &'a pavex::request::RequestHead,
            &'b sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
            &'c jsonwebtoken::EncodingKey,
            pavex::request::path::MatchedPathPattern,
        ) -> T,
    }
    impl<'a, 'b, 'c, T> std::future::IntoFuture for Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        type Output = pavex::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3, self.s_4)
        }
    }
    struct Next1<'a, 'b, 'c, 'd, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        s_0: &'a pavex_tracing::RootSpan,
        s_1: pavex::request::body::RawIncomingBody,
        s_2: &'b pavex::request::RequestHead,
        s_3: &'c sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_4: &'d jsonwebtoken::EncodingKey,
        next: fn(
            &'a pavex_tracing::RootSpan,
            pavex::request::body::RawIncomingBody,
            &'b pavex::request::RequestHead,
            &'c sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
            &'d jsonwebtoken::EncodingKey,
        ) -> T,
    }
    impl<'a, 'b, 'c, 'd, T> std::future::IntoFuture for Next1<'a, 'b, 'c, 'd, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        type Output = pavex::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3, self.s_4)
        }
    }
}
pub mod route_2 {
    pub async fn entrypoint<'a, 'b, 'c>(
        s_0: pavex::request::path::MatchedPathPattern,
        s_1: pavex::request::body::RawIncomingBody,
        s_2: &'a pavex::request::RequestHead,
        s_3: &'b sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_4: &'c jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let response = wrapping_0(s_0, s_1, s_2, s_3, s_4).await;
        response
    }
    async fn stage_1<'a, 'b, 'c>(
        s_0: pavex::request::body::RawIncomingBody,
        s_1: &'a pavex::request::RequestHead,
        s_2: &'b sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_3: &'c jsonwebtoken::EncodingKey,
        s_4: pavex::request::path::MatchedPathPattern,
    ) -> pavex::Response {
        let response = wrapping_1(s_0, s_4, s_1, s_2, s_3).await;
        response
    }
    async fn stage_2<'a, 'b, 'c, 'd>(
        s_0: &'a pavex_tracing::RootSpan,
        s_1: pavex::request::body::RawIncomingBody,
        s_2: &'b pavex::request::RequestHead,
        s_3: &'c sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_4: &'d jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let response = handler(s_1, s_2, s_0, s_3, s_4).await;
        let response = post_processing_0(response, s_0).await;
        response
    }
    async fn wrapping_0(
        v0: pavex::request::path::MatchedPathPattern,
        v1: pavex::request::body::RawIncomingBody,
        v2: &pavex::request::RequestHead,
        v3: &sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        v4: &jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let v5 = crate::route_2::Next0 {
            s_0: v1,
            s_1: v2,
            s_2: v3,
            s_3: v4,
            s_4: v0,
            next: stage_1,
        };
        let v6 = pavex::middleware::Next::new(v5);
        let v7 = pavex::middleware::wrap_noop(v6).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v7)
    }
    async fn wrapping_1(
        v0: pavex::request::body::RawIncomingBody,
        v1: pavex::request::path::MatchedPathPattern,
        v2: &pavex::request::RequestHead,
        v3: &sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        v4: &jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let v5 = pavex::telemetry::ServerRequestId::generate();
        let v6 = app::telemetry::root_span(v2, v1, v5);
        let v7 = crate::route_2::Next1 {
            s_0: &v6,
            s_1: v0,
            s_2: v2,
            s_3: v3,
            s_4: v4,
            next: stage_2,
        };
        let v8 = pavex::middleware::Next::new(v7);
        let v9 = <pavex_tracing::RootSpan as core::clone::Clone>::clone(&v6);
        let v10 = pavex_tracing::logger(v9, v8).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v10)
    }
    async fn handler(
        v0: pavex::request::body::RawIncomingBody,
        v1: &pavex::request::RequestHead,
        v2: &pavex_tracing::RootSpan,
        v3: &sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        v4: &jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let v5 = pavex::request::body::BodySizeLimit::new();
        let v6 = pavex::request::body::BufferedBody::extract(v1, v0, v5).await;
        let v7 = match v6 {
            Ok(ok) => ok,
            Err(v7) => {
                return {
                    let v8 = pavex::request::body::errors::ExtractBufferedBodyError::into_response(
                        &v7,
                    );
                    let v9 = pavex::Error::new(v7);
                    app::telemetry::error_logger(&v9, v2).await;
                    <pavex::Response as pavex::IntoResponse>::into_response(v8)
                };
            }
        };
        let v8 = pavex::request::body::JsonBody::extract(v1, &v7);
        let v9 = match v8 {
            Ok(ok) => ok,
            Err(v9) => {
                return {
                    let v10 = pavex::request::body::errors::ExtractJsonBodyError::into_response(
                        &v9,
                    );
                    let v11 = pavex::Error::new(v9);
                    app::telemetry::error_logger(&v11, v2).await;
                    <pavex::Response as pavex::IntoResponse>::into_response(v10)
                };
            }
        };
        let v10 = app::routes::users::signup(v9, v3, v4).await;
        let v11 = match v10 {
            Ok(ok) => ok,
            Err(v11) => {
                return {
                    let v12 = app::routes::users::SignupError::into_response(&v11);
                    let v13 = pavex::Error::new(v11);
                    app::telemetry::error_logger(&v13, v2).await;
                    <pavex::Response as pavex::IntoResponse>::into_response(v12)
                };
            }
        };
        <pavex::Response as pavex::IntoResponse>::into_response(v11)
    }
    async fn post_processing_0(
        v0: pavex::Response,
        v1: &pavex_tracing::RootSpan,
    ) -> pavex::Response {
        let v2 = app::telemetry::response_logger(v0, v1).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v2)
    }
    struct Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        s_0: pavex::request::body::RawIncomingBody,
        s_1: &'a pavex::request::RequestHead,
        s_2: &'b sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_3: &'c jsonwebtoken::EncodingKey,
        s_4: pavex::request::path::MatchedPathPattern,
        next: fn(
            pavex::request::body::RawIncomingBody,
            &'a pavex::request::RequestHead,
            &'b sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
            &'c jsonwebtoken::EncodingKey,
            pavex::request::path::MatchedPathPattern,
        ) -> T,
    }
    impl<'a, 'b, 'c, T> std::future::IntoFuture for Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        type Output = pavex::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3, self.s_4)
        }
    }
    struct Next1<'a, 'b, 'c, 'd, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        s_0: &'a pavex_tracing::RootSpan,
        s_1: pavex::request::body::RawIncomingBody,
        s_2: &'b pavex::request::RequestHead,
        s_3: &'c sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_4: &'d jsonwebtoken::EncodingKey,
        next: fn(
            &'a pavex_tracing::RootSpan,
            pavex::request::body::RawIncomingBody,
            &'b pavex::request::RequestHead,
            &'c sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
            &'d jsonwebtoken::EncodingKey,
        ) -> T,
    }
    impl<'a, 'b, 'c, 'd, T> std::future::IntoFuture for Next1<'a, 'b, 'c, 'd, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        type Output = pavex::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3, self.s_4)
        }
    }
}
pub mod route_3 {
    pub async fn entrypoint<'a, 'b, 'c>(
        s_0: pavex::request::path::MatchedPathPattern,
        s_1: pavex::request::body::RawIncomingBody,
        s_2: &'a pavex::request::RequestHead,
        s_3: &'b sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_4: &'c jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let response = wrapping_0(s_0, s_1, s_2, s_3, s_4).await;
        response
    }
    async fn stage_1<'a, 'b, 'c>(
        s_0: pavex::request::body::RawIncomingBody,
        s_1: &'a pavex::request::RequestHead,
        s_2: &'b sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_3: &'c jsonwebtoken::EncodingKey,
        s_4: pavex::request::path::MatchedPathPattern,
    ) -> pavex::Response {
        let response = wrapping_1(s_0, s_4, s_1, s_2, s_3).await;
        response
    }
    async fn stage_2<'a, 'b, 'c, 'd>(
        s_0: &'a pavex_tracing::RootSpan,
        s_1: pavex::request::body::RawIncomingBody,
        s_2: &'b pavex::request::RequestHead,
        s_3: &'c sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_4: &'d jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let response = handler(s_1, s_2, s_0, s_3, s_4).await;
        let response = post_processing_0(response, s_0).await;
        response
    }
    async fn wrapping_0(
        v0: pavex::request::path::MatchedPathPattern,
        v1: pavex::request::body::RawIncomingBody,
        v2: &pavex::request::RequestHead,
        v3: &sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        v4: &jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let v5 = crate::route_3::Next0 {
            s_0: v1,
            s_1: v2,
            s_2: v3,
            s_3: v4,
            s_4: v0,
            next: stage_1,
        };
        let v6 = pavex::middleware::Next::new(v5);
        let v7 = pavex::middleware::wrap_noop(v6).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v7)
    }
    async fn wrapping_1(
        v0: pavex::request::body::RawIncomingBody,
        v1: pavex::request::path::MatchedPathPattern,
        v2: &pavex::request::RequestHead,
        v3: &sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        v4: &jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let v5 = pavex::telemetry::ServerRequestId::generate();
        let v6 = app::telemetry::root_span(v2, v1, v5);
        let v7 = crate::route_3::Next1 {
            s_0: &v6,
            s_1: v0,
            s_2: v2,
            s_3: v3,
            s_4: v4,
            next: stage_2,
        };
        let v8 = pavex::middleware::Next::new(v7);
        let v9 = <pavex_tracing::RootSpan as core::clone::Clone>::clone(&v6);
        let v10 = pavex_tracing::logger(v9, v8).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v10)
    }
    async fn handler(
        v0: pavex::request::body::RawIncomingBody,
        v1: &pavex::request::RequestHead,
        v2: &pavex_tracing::RootSpan,
        v3: &sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        v4: &jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let v5 = pavex::request::body::BodySizeLimit::new();
        let v6 = pavex::request::body::BufferedBody::extract(v1, v0, v5).await;
        let v7 = match v6 {
            Ok(ok) => ok,
            Err(v7) => {
                return {
                    let v8 = pavex::request::body::errors::ExtractBufferedBodyError::into_response(
                        &v7,
                    );
                    let v9 = pavex::Error::new(v7);
                    app::telemetry::error_logger(&v9, v2).await;
                    <pavex::Response as pavex::IntoResponse>::into_response(v8)
                };
            }
        };
        let v8 = pavex::request::body::JsonBody::extract(v1, &v7);
        let v9 = match v8 {
            Ok(ok) => ok,
            Err(v9) => {
                return {
                    let v10 = pavex::request::body::errors::ExtractJsonBodyError::into_response(
                        &v9,
                    );
                    let v11 = pavex::Error::new(v9);
                    app::telemetry::error_logger(&v11, v2).await;
                    <pavex::Response as pavex::IntoResponse>::into_response(v10)
                };
            }
        };
        let v10 = app::routes::users::login(v9, v3, v4).await;
        let v11 = match v10 {
            Ok(ok) => ok,
            Err(v11) => {
                return {
                    let v12 = app::routes::users::LoginError::into_response(&v11);
                    let v13 = pavex::Error::new(v11);
                    app::telemetry::error_logger(&v13, v2).await;
                    <pavex::Response as pavex::IntoResponse>::into_response(v12)
                };
            }
        };
        <pavex::Response as pavex::IntoResponse>::into_response(v11)
    }
    async fn post_processing_0(
        v0: pavex::Response,
        v1: &pavex_tracing::RootSpan,
    ) -> pavex::Response {
        let v2 = app::telemetry::response_logger(v0, v1).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v2)
    }
    struct Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        s_0: pavex::request::body::RawIncomingBody,
        s_1: &'a pavex::request::RequestHead,
        s_2: &'b sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_3: &'c jsonwebtoken::EncodingKey,
        s_4: pavex::request::path::MatchedPathPattern,
        next: fn(
            pavex::request::body::RawIncomingBody,
            &'a pavex::request::RequestHead,
            &'b sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
            &'c jsonwebtoken::EncodingKey,
            pavex::request::path::MatchedPathPattern,
        ) -> T,
    }
    impl<'a, 'b, 'c, T> std::future::IntoFuture for Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        type Output = pavex::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3, self.s_4)
        }
    }
    struct Next1<'a, 'b, 'c, 'd, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        s_0: &'a pavex_tracing::RootSpan,
        s_1: pavex::request::body::RawIncomingBody,
        s_2: &'b pavex::request::RequestHead,
        s_3: &'c sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_4: &'d jsonwebtoken::EncodingKey,
        next: fn(
            &'a pavex_tracing::RootSpan,
            pavex::request::body::RawIncomingBody,
            &'b pavex::request::RequestHead,
            &'c sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
            &'d jsonwebtoken::EncodingKey,
        ) -> T,
    }
    impl<'a, 'b, 'c, 'd, T> std::future::IntoFuture for Next1<'a, 'b, 'c, 'd, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        type Output = pavex::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3, self.s_4)
        }
    }
}
pub mod route_4 {
    pub async fn entrypoint<'a, 'b, 'c>(
        s_0: pavex::request::path::MatchedPathPattern,
        s_1: pavex::request::body::RawIncomingBody,
        s_2: &'a pavex::request::RequestHead,
        s_3: &'b sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_4: &'c jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let response = wrapping_0(s_0, s_1, s_2, s_3, s_4).await;
        response
    }
    async fn stage_1<'a, 'b, 'c>(
        s_0: pavex::request::body::RawIncomingBody,
        s_1: &'a pavex::request::RequestHead,
        s_2: &'b sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_3: &'c jsonwebtoken::EncodingKey,
        s_4: pavex::request::path::MatchedPathPattern,
    ) -> pavex::Response {
        let response = wrapping_1(s_0, s_4, s_1, s_2, s_3).await;
        response
    }
    async fn stage_2<'a, 'b, 'c, 'd>(
        s_0: &'a pavex_tracing::RootSpan,
        s_1: pavex::request::body::RawIncomingBody,
        s_2: &'b pavex::request::RequestHead,
        s_3: &'c sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_4: &'d jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let response = handler(s_1, s_2, s_0, s_3, s_4).await;
        let response = post_processing_0(response, s_0).await;
        response
    }
    async fn wrapping_0(
        v0: pavex::request::path::MatchedPathPattern,
        v1: pavex::request::body::RawIncomingBody,
        v2: &pavex::request::RequestHead,
        v3: &sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        v4: &jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let v5 = crate::route_4::Next0 {
            s_0: v1,
            s_1: v2,
            s_2: v3,
            s_3: v4,
            s_4: v0,
            next: stage_1,
        };
        let v6 = pavex::middleware::Next::new(v5);
        let v7 = pavex::middleware::wrap_noop(v6).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v7)
    }
    async fn wrapping_1(
        v0: pavex::request::body::RawIncomingBody,
        v1: pavex::request::path::MatchedPathPattern,
        v2: &pavex::request::RequestHead,
        v3: &sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        v4: &jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let v5 = pavex::telemetry::ServerRequestId::generate();
        let v6 = app::telemetry::root_span(v2, v1, v5);
        let v7 = crate::route_4::Next1 {
            s_0: &v6,
            s_1: v0,
            s_2: v2,
            s_3: v3,
            s_4: v4,
            next: stage_2,
        };
        let v8 = pavex::middleware::Next::new(v7);
        let v9 = <pavex_tracing::RootSpan as core::clone::Clone>::clone(&v6);
        let v10 = pavex_tracing::logger(v9, v8).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v10)
    }
    async fn handler(
        v0: pavex::request::body::RawIncomingBody,
        v1: &pavex::request::RequestHead,
        v2: &pavex_tracing::RootSpan,
        v3: &sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        v4: &jsonwebtoken::EncodingKey,
    ) -> pavex::Response {
        let v5 = pavex::request::body::BodySizeLimit::new();
        let v6 = pavex::request::body::BufferedBody::extract(v1, v0, v5).await;
        let v7 = match v6 {
            Ok(ok) => ok,
            Err(v7) => {
                return {
                    let v8 = pavex::request::body::errors::ExtractBufferedBodyError::into_response(
                        &v7,
                    );
                    let v9 = pavex::Error::new(v7);
                    app::telemetry::error_logger(&v9, v2).await;
                    <pavex::Response as pavex::IntoResponse>::into_response(v8)
                };
            }
        };
        let v8 = pavex::request::body::JsonBody::extract(v1, &v7);
        let v9 = match v8 {
            Ok(ok) => ok,
            Err(v9) => {
                return {
                    let v10 = pavex::request::body::errors::ExtractJsonBodyError::into_response(
                        &v9,
                    );
                    let v11 = pavex::Error::new(v9);
                    app::telemetry::error_logger(&v11, v2).await;
                    <pavex::Response as pavex::IntoResponse>::into_response(v10)
                };
            }
        };
        let v10 = app::routes::users::signup(v9, v3, v4).await;
        let v11 = match v10 {
            Ok(ok) => ok,
            Err(v11) => {
                return {
                    let v12 = app::routes::users::SignupError::into_response(&v11);
                    let v13 = pavex::Error::new(v11);
                    app::telemetry::error_logger(&v13, v2).await;
                    <pavex::Response as pavex::IntoResponse>::into_response(v12)
                };
            }
        };
        <pavex::Response as pavex::IntoResponse>::into_response(v11)
    }
    async fn post_processing_0(
        v0: pavex::Response,
        v1: &pavex_tracing::RootSpan,
    ) -> pavex::Response {
        let v2 = app::telemetry::response_logger(v0, v1).await;
        <pavex::Response as pavex::IntoResponse>::into_response(v2)
    }
    struct Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        s_0: pavex::request::body::RawIncomingBody,
        s_1: &'a pavex::request::RequestHead,
        s_2: &'b sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_3: &'c jsonwebtoken::EncodingKey,
        s_4: pavex::request::path::MatchedPathPattern,
        next: fn(
            pavex::request::body::RawIncomingBody,
            &'a pavex::request::RequestHead,
            &'b sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
            &'c jsonwebtoken::EncodingKey,
            pavex::request::path::MatchedPathPattern,
        ) -> T,
    }
    impl<'a, 'b, 'c, T> std::future::IntoFuture for Next0<'a, 'b, 'c, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        type Output = pavex::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3, self.s_4)
        }
    }
    struct Next1<'a, 'b, 'c, 'd, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        s_0: &'a pavex_tracing::RootSpan,
        s_1: pavex::request::body::RawIncomingBody,
        s_2: &'b pavex::request::RequestHead,
        s_3: &'c sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
        s_4: &'d jsonwebtoken::EncodingKey,
        next: fn(
            &'a pavex_tracing::RootSpan,
            pavex::request::body::RawIncomingBody,
            &'b pavex::request::RequestHead,
            &'c sqlx_core::pool::Pool<sqlx_sqlite::Sqlite>,
            &'d jsonwebtoken::EncodingKey,
        ) -> T,
    }
    impl<'a, 'b, 'c, 'd, T> std::future::IntoFuture for Next1<'a, 'b, 'c, 'd, T>
    where
        T: std::future::Future<Output = pavex::Response>,
    {
        type Output = pavex::Response;
        type IntoFuture = T;
        fn into_future(self) -> Self::IntoFuture {
            (self.next)(self.s_0, self.s_1, self.s_2, self.s_3, self.s_4)
        }
    }
}
