# This file contains the configuration for the dev environment.
# None of the values here are actually secret, so it's fine
# to commit this file to the repository.
server:
  ip: "127.0.0.1"
  port: 8000

database:
  database_url: "sqlite:./data/app.db"
  create_if_missing: true

session:
  cookie:
    name: "session"
    secure: false
    http_only: true
    same_site: "Lax"
  state:
    ttl: "168h"

auth:
  eddsa_private_key_pem: "placeholder"
  eddsa_public_key_pem: "placeholder"
